// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Livraria.Model.Models;

public partial class Alugado
{
    [Key]
    [Column("id")]
    [DisplayName("Código")]
    public int Id { get; set; }

    [Column("idCliente")]
    [DisplayName("Código do Cliente")]
    public int IdCliente { get; set; }

    [Column("idLivro")]
    [DisplayName("Código do Livro")]
    public int IdLivro { get; set; }

    [Column("dataRetorno", TypeName = "date")]
    [DisplayName("Data de Retorno")]
    public DateTime DataRetorno { get; set; }

    [Column("retornado")]
    public bool Retornado { get; set; }

    [ForeignKey("IdCliente")]
    [InverseProperty("Alugado")]
    public virtual Cliente IdClienteNavigation { get; set; }

    [ForeignKey("IdLivro")]
    [InverseProperty("Alugado")]
    public virtual Livro IdLivroNavigation { get; set; }

    [InverseProperty("Alugado")]
    public virtual ICollection<ItemAlugado> ItemAlugado { get; set; } = new List<ItemAlugado>();




}