// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Livraria.Model.Models;

public partial class Cliente
{
    [Key]
    [Column("id")]
    [DisplayName("Código")]
    [HiddenInput(DisplayValue = false)]
    public int Id { get; set; }

    [Required]
    [Column("nome")]
    [StringLength(80)]
    [Unicode(false)]
    public string Nome { get; set; }

    [Required]
    [Column("endereco")]
    [StringLength(80)]
    [Unicode(false)]
    [DisplayName("Endereço")]
    public string Endereco { get; set; }

    [Required]
    [Column("telefone")]
    [StringLength(20)]
    [Unicode(false)]
    public string Telefone { get; set; }

    [Required]
    [Column("email")]
    [StringLength(120)]
    [Unicode(false)]
    public string Email { get; set; }

    [InverseProperty("IdClienteNavigation")]
    public virtual ICollection<Alugado> Alugado { get; set; } = new List<Alugado>();

    [InverseProperty("IdClienteNavigation")]
    public virtual ICollection<ItemAlugado> ItemAlugado { get; set; } = new List<ItemAlugado>();
}